import { defineConfig } from 'astro/config';

// 中文为主：默认语言 zh（无前缀），英文在 /en/ 下
// base = 项目页子路径（naphjohn.github.io 用户页已被占用，Astro 放新仓库作项目页）
export default defineConfig({
  site: 'https://naphjohn.github.io',
  base: '/stock-blog/',
  i18n: {
    defaultLocale: 'zh',
    locales: ['zh', 'en'],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  // 旧 kb01–31 已合并为 K01–K10；保留旧 URL 重定向，不丢链
  redirects: {
    '/blog/kb01': '/stock-blog/blog/K01',
    '/en/blog/kb01': '/stock-blog/en/blog/K01',
    '/blog/kb02': '/stock-blog/blog/K01',
    '/en/blog/kb02': '/stock-blog/en/blog/K01',
    '/blog/kb03': '/stock-blog/blog/K01',
    '/en/blog/kb03': '/stock-blog/en/blog/K01',
    '/blog/kb04': '/stock-blog/blog/K01',
    '/en/blog/kb04': '/stock-blog/en/blog/K01',
    '/blog/kb05': '/stock-blog/blog/K02',
    '/en/blog/kb05': '/stock-blog/en/blog/K02',
    '/blog/kb06': '/stock-blog/blog/K02',
    '/en/blog/kb06': '/stock-blog/en/blog/K02',
    '/blog/kb07': '/stock-blog/blog/K03',
    '/en/blog/kb07': '/stock-blog/en/blog/K03',
    '/blog/kb08': '/stock-blog/blog/K03',
    '/en/blog/kb08': '/stock-blog/en/blog/K03',
    '/blog/kb09': '/stock-blog/blog/K04',
    '/en/blog/kb09': '/stock-blog/en/blog/K04',
    '/blog/kb10': '/stock-blog/blog/K04',
    '/en/blog/kb10': '/stock-blog/en/blog/K04',
    '/blog/kb11': '/stock-blog/blog/K05',
    '/en/blog/kb11': '/stock-blog/en/blog/K05',
    '/blog/kb12': '/stock-blog/blog/K05',
    '/en/blog/kb12': '/stock-blog/en/blog/K05',
    '/blog/kb13': '/stock-blog/blog/K05',
    '/en/blog/kb13': '/stock-blog/en/blog/K05',
    '/blog/kb14': '/stock-blog/blog/K05',
    '/en/blog/kb14': '/stock-blog/en/blog/K05',
    '/blog/kb15': '/stock-blog/blog/K05',
    '/en/blog/kb15': '/stock-blog/en/blog/K05',
    '/blog/kb16': '/stock-blog/blog/K06',
    '/en/blog/kb16': '/stock-blog/en/blog/K06',
    '/blog/kb17': '/stock-blog/blog/K06',
    '/en/blog/kb17': '/stock-blog/en/blog/K06',
    '/blog/kb18': '/stock-blog/blog/K06',
    '/en/blog/kb18': '/stock-blog/en/blog/K06',
    '/blog/kb19': '/stock-blog/blog/K06',
    '/en/blog/kb19': '/stock-blog/en/blog/K06',
    '/blog/kb20': '/stock-blog/blog/K07',
    '/en/blog/kb20': '/stock-blog/en/blog/K07',
    '/blog/kb21': '/stock-blog/blog/K07',
    '/en/blog/kb21': '/stock-blog/en/blog/K07',
    '/blog/kb22': '/stock-blog/blog/K07',
    '/en/blog/kb22': '/stock-blog/en/blog/K07',
    '/blog/kb23': '/stock-blog/blog/K08',
    '/en/blog/kb23': '/stock-blog/en/blog/K08',
    '/blog/kb24': '/stock-blog/blog/K08',
    '/en/blog/kb24': '/stock-blog/en/blog/K08',
    '/blog/kb25': '/stock-blog/blog/K08',
    '/en/blog/kb25': '/stock-blog/en/blog/K08',
    '/blog/kb26': '/stock-blog/blog/K09',
    '/en/blog/kb26': '/stock-blog/en/blog/K09',
    '/blog/kb27': '/stock-blog/blog/K09',
    '/en/blog/kb27': '/stock-blog/en/blog/K09',
    '/blog/kb28': '/stock-blog/blog/K09',
    '/en/blog/kb28': '/stock-blog/en/blog/K09',
    '/blog/kb29': '/stock-blog/blog/K10',
    '/en/blog/kb29': '/stock-blog/en/blog/K10',
    '/blog/kb30': '/stock-blog/blog/K10',
    '/en/blog/kb30': '/stock-blog/en/blog/K10',
    '/blog/kb31': '/stock-blog/blog/K10',
    '/en/blog/kb31': '/stock-blog/en/blog/K10',
  },
});
